image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - gradle
         script:
          - './gradlew build'
         artifacts:
          - build/libs/modid-1.0.jar